require: rubocop-rails
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - config/initializers/secret_token.rb

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/BlockLength:
    Max: 30
    Exclude:
      - 'Rakefile'
      - '**/*.rake'
      - 'spec/**/*.rb'
