require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - config/initializers/secret_token.rb

RSpec:
  Language:
    Includes:
      Examples:
        - response
        - run_test!

Layout/LineLength:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false


Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'db/migrate/*'

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - 'app/serializers/**/*'

Performance/RedundantBlockCall:
  Enabled: false

# false positives
Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/VariableName:
  Exclude:
    - 'spec/**/*'

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods: [ insert_all, update_all, upsert_all ]
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  AllowedMethods: [ descr
    Exclude:
      - 'config/**/*'
      - 'db/migrate/*'
      - 'Rakefile'
      - '**/*.rake'
      - 'spec/**/*.rb'
