export const LOADING_PROFILE = "LOADING_PROFILE"
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"
export const LOAD_PROFILE_FAILED = "LOAD_PROFILE_FAILED"

export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS'
export const SAVE_PROFILE_FAILED = 'SAVE_PROFILE_FAILED'

export const LOADING_BALANCE ='LOADING_BALANCE'

export const LOAD_SELF_BALANCE_SUCCESS = 'LOAD_SELF_BALANCE_SUCCESS'
export const LOAD_SELF_BALANCE_FAILED = 'LOAD_SELF_BALANCE_FAILED'

export const LOAD_DISTRIB_BALANCE_SUCCESS = 'LOAD_DISTRIB_BALANCE_SUCCESS'
export const LOAD_DISTRIB_BALANCE_FAILED = 'LOAD_DISTRIB_BALANCE_FAILED'


export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS'
export const CONFIRM_EMAIL_FAILED  = 'CONFIRM_EMAIL_FAILED'


export const PASSWORD_RECOVER_SUCCESS = "PASSWORD_RECOVER_SUCCESS"
export const PASSWORD_RECOVER_FAILED = "PASSWORD_RECOVER_FAILED"
