export const LOADING_PROFILE = "LOADING_PROFILE"
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"
export const LOAD_PROFILE_FAILED = "LOAD_PROFILE_FAILED"

export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS'
export const SAVE_PROFILE_FAILED = 'SAVE_PROFILE_FAILED'
