production:
  link_template: "link_template"
  default_template: "link_template"
development:
  link_template: "link_template"
  default_template: "link_template"
staging:
  link_template: "link_template"
  default_template: "link_template"
test:
    link_template: "link_template"
    default_template: "link_template"
