export const AUTHENTICATE ='AUTHENTICATE'

export const AUTHENTICATE_SUCCESS ='AUTHENTICATE_SUCCESS'
export const AUTHENTICATE_FAILED ='AUTHENTICATE_FAILED'
export const LOG_OUT ='LOG_OUT'
export const REGISTER ='REGISTER'
export const REGISTER_SUCCESS ='REGISTER_SUCCESS'
export const REGISTER_FAILED ='REGISTER_FAILED'


export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'


export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
