export const LOADING_ACCOUNT = "LOADING_ACCOUNT"
export const LOAD_ACCOUNT_SUCCESS = "LOAD_ACCOUNT_SUCCESS"
export const LOAD_ACCOUNT_FAILED = "LOAD_ACCOUNT_FAILED"

export const SAVE_ACCOUNT_SUCCESS = 'SAVE_ACCOUNT_SUCCESS'
export const SAVE_ACCOUNT_FAILED = 'SAVE_ACCOUNT_FAILED'
